### ISSUE TITLE
there is no  differentiable_MD in deepab.build_fv.mds

### ISSUE THREAD

**Issue by pickpingk** [RosettaCommons/DeepAb#12]
I want try to run the code,but i found that the class(deepab.build_fv.mds) don't have the function(differentiable_MD),  which was referenced in the class(H5PairwiseGeometryDataset)

**Comment by jeffreyruffolo** [comment]
Thank you for pointing this out! I've gone through and cleaned up the training dataset generation code. Could you try again and see if you run into any other issues?

**Comment by jeffreyruffolo** [comment]
Closing this issue for now, but please reopen if the problem remains.
