### ISSUE TITLE
Internet requirement problem

### ISSUE THREAD

**Issue by zenghk** [RosettaCommons/DeepAb#13]
I am a student which major in BCR sequencing, and I am trying to run the DaapAb on my HPC to predict some structure of some BCR, however, some errors exist, such as the following, After re-check the environment, I think the problem may be the requirement of response. Requirement files include some package such as beatuifulsoup and requests,  which seems to be request for some information from an online website. However, our HPC is stored in the hospital and only login node is accessible, when I submit the files to run on other compute node to run multiple sequences in the same time, network is not available for these node. Is there any solution for network-free enviroment?
Thanks

new_pdb_data = response.text
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by everyday847** [comment]
The usage in `pdb.py` is only for antibody renumbering, which could be computed locally via software like ANARCI. (It's also not a computationally intensive step, so you could handle it locally on your laptop or even on the login node. If anything, that would be faster!) 

The import in `util.py` is never used.

And the import in `create_antibody_db.py` is used but that's only relevant if you want to download a very specific benchmark set, using Python.

Generally speaking, I suggest _not renumbering_ and using separate software to renumber antibody structures when needed.

**Comment by zenghk** [comment]
thanks for your reply, I have changed the node for the script and run the example files in data folder successfully, and I will test my own files later.

**Comment by jeffreyruffolo** [comment]
Thanks for pointing this out, as @everyday847 suggested I would avoid using the `--renumber` flag if you do not have internet access, as that option will attempt to renumber your structure via the AbNum server. I've added an error message to note that if the AbNum request fails it's likely due to an internet issue.
