### ISSUE TITLE
Technical problems

### ISSUE THREAD

**Issue by Tofindcode** [RosettaCommons/DeepAb#17]
Hi,
I am a rookie in antibody structure prediction, how should I get the exact Fv seq from fasta file of full-length?

Thanks

**Comment by jeffreyruffolo** [comment]
One quick way to get numbering is to run each sequence through the [AbNum server](http://www.bioinf.org.uk/abs/abnum/). This will give you a per residue number, excluding the extra residues. Then you can see how much of each chain to use for input to DeepAb.

**Comment by Tofindcode** [comment]
Thank you so much for your reply!
