### ISSUE TITLE
issue when running the demo

### ISSUE THREAD

**Issue by jlspzw** [RosettaCommons/DeepAb#20]
After I have done the install, when I run the demo sequence, I got an issue like

Generating constraints
**************************************************
/xxx/bin/python/miniconda3/envs/deepab/lib/python3.7/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")

**************************************************
Creating MDS structure
**************************************************

ERROR: The x and/or y axis lines in the given spline are empty
x_axis: []
y_axis: []

ERROR:: Exit from: /scratch/benchmark/W.hojo-2/rosetta.Hojo-2/_commits_/main/source/src/numeric/interpolation/util.cc line: 51

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/xxx/bin/python/miniconda3/envs/deepab/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/xxx/bin/python/miniconda3/envs/deepab/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/xxx/bin/python/miniconda3/envs/deepab/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "predict.py", line 29, in refine_fv_
    return refine_fv(in_pdb_file, out_pdb_file, cst_defs)
  File "/xxx/ProteinFolding/DeepAb/deepab/build_fv/build_cen_fa.py", line 207, in refine_fv
    pose)
RuntimeError: 

File: /scratch/benchmark/W.hojo-2/rosetta.Hojo-2/_commits_/main/source/src/numeric/interpolation/util.cc:51
[ ERROR ] UtilityExitException
ERROR: The x and/or y axis lines in the given spline are empty
x_axis: []
y_axis: []

COuld you help to check what is the issue?

**Comment by jeffreyruffolo** [comment]
Hi, any chance you can share the sequence you are trying to predict? I expect that if Rosetta is failing to produce constraints it could be that the input sequence isn't truncated to just the Fv. This may cause the model to produce strange output that isn't well-handled by Rosetta.

**Comment by jlspzw** [comment]
Hi

I tested the demo sequence in the data folder provided by the package. It seems the issue is from old PyRosetta (one year ago), I tried to download the newest version PyRosetta. There is not any issue now. Thank you.

**Comment by jeffreyruffolo** [comment]
Great, glad it's working now!
